### PR TITLE
Remove yang OC models

### PR DESCRIPTION
**Pull request by dplore**
Removing the openconfig yang models from the gNSI repository as they are now moved to the [openconfig public repository]( https://github.com/openconfig/public) via https://github.com/openconfig/public/pull/1037

### CODE REVIEW

**Comment by brianneville** [comment]
https://github.com/openconfig/public/pull/1037 included an outdated version of gNSI Certz, which has been since updated so that the counter names are different (`connection-accepts`/`connection-rejects`/`last-connection-accept`/`last-connection-reject` vs `access-accepts`/`access-rejects`/`last-access-accept`/`last-access-reject`), and the description of these counters has been updated.

see:
https://github.com/openconfig/gnsi/blob/e05f3dc38e6956c8af0ffcd3f9c0c24c5cf2d295/certz/gnsi-certz.yang#L84-L109

modified as of https://github.com/openconfig/gnsi/pull/156

**Comment by brianneville** [comment]
I've opened a PR to resolve this, please take a look:
https://github.com/openconfig/public/pull/1061

**Comment by dplore** [comment]
Thanks, will wait to merge this until the changes you proposed are merged just for ease of reference

**Comment by dplore** [comment]
@marcushines could use your approval to merge this to prevent confusion (such as #175 )

**Comment by dplore** [comment]
> Please mention in the respective READMEs that the models have moved and whither.

Done

**Review by marcushines — APPROVED** [review]

**Review by marcushines — APPROVED** [review]

**Pull request merged**
